# yaml-language-server: $schema=https://raw.githubusercontent.com/cncf/landscape2/refs/heads/main/docs/config/schema/settings.schema.json

foundation: AAIF
url: https://aaif.landscape2.io

members_category: Members

groups:
  - name: Projects
    alias: projects
    categories:
      - Agentic AI Momentum Watchlist
  - name: Members
    alias: members
    categories:
      - Members

categories:
  - name: Members
    subcategories:
      - Platinum
      - Gold
      - Silver
      - Associate
  - name: Agentic AI Momentum Watchlist
    subcategories:
      - Gateway & Control Plane
      - Agentic Runtime
      - Protocols & Interfaces
      - Data & Knowledge
      - Agentic Development

featured_items:
  - field: maturity
    options:
      - value: member
        order: 1
        label: AAIF Member Project
    exclude:
      groups:
        - Members
